

module.exports = () => {

  return (html, { status, date, url, seconds }) => {

    return html.replace(/<head[^>]*>/i, (match) => {
      return match + `<!-- Generated by WebRenderer (Url: ${encodeURI(url)}, Status: ${status}, Time: ${seconds.toFixed(3)} sec, Date: ${date.toISOString()}) -->`
    });

  }

};